service: ts-with-node18
useDotenv: true

plugins:
  - serverless-esbuild # used for compiling/packaging the Typescript code
  - serverless-offline # used for local execution
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  stage: dev
  #timeout: 30   # repository wide Lambda timeout
  environment:  # repository wide Lambda env variables
    TABLE_NAME: ${env:TABLE_NAME}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${env:REGION}
    STAGE: ${self:provider.stage}

custom:
  customVariable1: Hello, World!

functions:
  # Serverless Framework specific syntax
  Function1:
    handler: ./src/lambda1.handler
    events:
      - httpApi:
          path: /api/Function1
          method: GET
    environment:
      CUSTOM_VAR: ${self:custom.customVariable1}

  Function2:
    handler: ./src/lambda2.handler
    timeout: 10        # override global setting
    memorySize: 2048   # override default 512 Mb
    events:
      - schedule:
          rate: cron(0 12 * * ? *) # triggers every 12 hours
          enabled: true
  api:
    handler: ./src/index.handler
    events:
       - http: 
          path: /characters
          method: GET
       - http: 
          path: /characters/{id}
          method: GET
       - http:
          path: /envVariables
          method: GET
       - http:
          path: /bulkData
          method: POST          
